// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YGHMS.API.Infra;

#nullable disable

namespace YGHMS.API.Migrations
{
    [DbContext(typeof(RentalManagementContext))]
    [Migration("20231101024447_update-follow_reservation")]
    partial class updatefollow_reservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AddressPublication", b =>
                {
                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("AddressId", "MediaId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MediaId" }, "Address_Media_detaillmedia_Id_fk");

                    b.ToTable("Address_Publication", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(6000)
                        .HasColumnType("varchar(6000)");

                    b.Property<string>("DetailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("EstateTypesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Expiration")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Policies")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<decimal?>("Quality")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AddressId" }, "Accommodations_addresses_Id_fk");

                    b.HasIndex(new[] { "EstateTypesId" }, "ForeignKey_Accommodations_EstateTypes_idx");

                    b.HasIndex(new[] { "OwnerId" }, "ForeignKey_Accommodations_User_idx");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.AccommodationPublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MediaId" }, "FK_Accomodation_Media_Media_idx");

                    b.HasIndex(new[] { "AccommodationId" }, "FK_accommodation_media_Accommdation_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE")
                        .IsUnique();

                    b.ToTable("accommodation_publication", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Emai")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "UserId_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UserName_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "accounts_userer_roleId_idx");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Commune")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Detail")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Media")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE1")
                        .IsUnique();

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE2")
                        .IsUnique();

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<float?>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxOccupant")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("NumberOfBed")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfBed")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccommodationId" }, "FK_Apartment_Accom_idx");

                    b.HasIndex(new[] { "OwnerId" }, "FK_Apartment_User_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE3")
                        .IsUnique();

                    b.ToTable("apartments", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentBedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<sbyte>("IsDelete")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApartmentId" }, "Apartment_BedType_ApartmentId_index");

                    b.HasIndex(new[] { "ApartmentId", "Type" }, "Apartment_BedType_pk2")
                        .IsUnique();

                    b.ToTable("Apartment_BedType", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<sbyte>("IsDelete")
                        .HasColumnType("tinyint")
                        .HasColumnName("isDelete");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApartmentId" }, "ApartmentBenefits_ApartmentId_index");

                    b.ToTable("ApartmentBenefits");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentPublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApartmentId" }, "FK_Apartment_Media_Apartment_idx");

                    b.HasIndex(new[] { "MediaId" }, "FK_Apartment_Media_Media_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE4")
                        .IsUnique();

                    b.ToTable("apartment_publication", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentsAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AmenityId" }, "FK_Amenity_idx");

                    b.HasIndex(new[] { "ApartmentId" }, "FK_Apartment_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE5")
                        .IsUnique();

                    b.ToTable("apartments_amenities", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ReceivedId")
                        .HasColumnType("int");

                    b.Property<int>("SendedId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SendedId", "ReceivedId" }, "FK_Chat_Sender_idx");

                    b.HasIndex(new[] { "ReceivedId" }, "FK_Chat_User_Receiver_idx");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique();

                    b.ToTable("chat", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Estatetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "EstateType_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE7")
                        .IsUnique();

                    b.ToTable("estatetypes", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.FollowUserAccom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccomodationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccomodationId" }, "FK_Follow_Accom_idx");

                    b.HasIndex(new[] { "UserId" }, "FK_Follow_User_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE8")
                        .IsUnique();

                    b.ToTable("follow_user_accom", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<sbyte>("IsRead")
                        .HasColumnType("tinyint")
                        .HasColumnName("isRead");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE9")
                        .IsUnique();

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.NotificationFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FollowId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("FollowId");

                    b.HasIndex(new[] { "NotificationId" }, "FK_Notification_Follow_Notification_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE10")
                        .IsUnique();

                    b.ToTable("Notification_follow", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.NotificationReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NotificationId" }, "FK_Notification_reservation_Notification_idx");

                    b.HasIndex(new[] { "ReservationId" }, "FK_Notification_reservation_Reservation_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE11")
                        .IsUnique();

                    b.ToTable("Notification_reservation", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.NotificationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NotifycatonId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NotifycatonId" }, "FK_Notification_Review_Notification_idx");

                    b.HasIndex(new[] { "ReviewId" }, "FK_Notification_Review_Review_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE12")
                        .IsUnique();

                    b.ToTable("Notification_review", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE6")
                        .IsUnique();

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("reasons", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ReasonReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReasonId")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReasonId" }, "FK_Reason_Report_Reason_idx");

                    b.HasIndex(new[] { "ReportId" }, "FK_Reason_Report_Report_idx");

                    b.ToTable("reason_report", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccomodationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccomodationId" }, "FK_Report_Accommodation_idx");

                    b.HasIndex(new[] { "UserId" }, "FK_Report_user_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE13")
                        .IsUnique();

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("BedType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FromDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApartmentId" }, "FK_Reservation_Apartment_idx");

                    b.HasIndex(new[] { "OwnerId" }, "FK_Reservation_User_Owner_idx");

                    b.HasIndex(new[] { "UserId" }, "FK_User_idx");

                    b.HasIndex(new[] { "Id" }, "idReservation_UNIQUE")
                        .IsUnique();

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE14")
                        .IsUnique();

                    b.HasIndex(new[] { "ReservationId" }, "reviews_reservation_Id_fk");

                    b.HasIndex(new[] { "UserId" }, "reviews_users_Id_fk");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<sbyte>("IsDelete")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "Id" }, "Transactions_Id_index");

                    b.HasIndex(new[] { "PostId" }, "Transactions_PostId_index");

                    b.HasIndex(new[] { "UserId" }, "Transactions_UserId_index");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Unavailableapartmentdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartmentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Apartment_TypeId");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApartmentTypeId" }, "FK_Âprartment_idx");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE15")
                        .IsUnique();

                    b.ToTable("unavailableapartmentdate", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<int?>("CoverImage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("ModifyAt")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleId" }, "ForeignKey_Users_Role_idx");

                    b.HasIndex(new[] { "AvatarId" }, "users_Publications_Id_fk");

                    b.HasIndex(new[] { "CoverImage" }, "users_Publications_Id_fk2");

                    b.HasIndex(new[] { "UserName" }, "users_pk")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.UserHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<sbyte>("IsDelete")
                        .HasColumnType("tinyint")
                        .HasColumnName("isDelete");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime")
                        .HasColumnName("modifyAt");

                    b.Property<int?>("PublicationId")
                        .HasColumnType("int")
                        .HasColumnName("publication_id");

                    b.Property<int?>("Title")
                        .HasColumnType("int")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PublicationId" }, "user_highlight_Publications_Id_fk");

                    b.HasIndex(new[] { "UserId", "PublicationId" }, "user_highlight_pk2")
                        .IsUnique();

                    b.ToTable("user_highlight", (string)null);
                });

            modelBuilder.Entity("AddressPublication", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("Address_Media_addresses_Id_fk");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Publication", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .IsRequired()
                        .HasConstraintName("Address_Media_detaillmedia_Id_fk");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Accommodation", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Address", "Address")
                        .WithMany("Accommodations")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("Accommodations_addresses_Id_fk");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Estatetype", "EstateTypes")
                        .WithMany("Accommodations")
                        .HasForeignKey("EstateTypesId")
                        .HasConstraintName("ForeignKey_Accommodations_EstateTypes");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "Owner")
                        .WithMany("Accommodations")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("ForeignKey_Accommodations_User");

                    b.Navigation("Address");

                    b.Navigation("EstateTypes");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.AccommodationPublication", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Accommodation", "Accommodation")
                        .WithMany("AccommodationPublications")
                        .HasForeignKey("AccommodationId")
                        .IsRequired()
                        .HasConstraintName("FK_Accommodation_Media_Accommodation");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Publication", "Media")
                        .WithMany("AccommodationPublications")
                        .HasForeignKey("MediaId")
                        .HasConstraintName("FK_Accomodation_Media_Media");

                    b.Navigation("Accommodation");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Account", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("ForeignKey_accounts_userer");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("YghRentalManagementSystem.Infra.Models.Account", "UserId")
                        .IsRequired()
                        .HasConstraintName("ForignKey_accounts_users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Apartment", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Accommodation", "Accommodation")
                        .WithMany("Apartments")
                        .HasForeignKey("AccommodationId")
                        .IsRequired()
                        .HasConstraintName("FK_Apartment_Accom");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "Owner")
                        .WithMany("Apartments")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Apartment_User");

                    b.Navigation("Accommodation");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentBedType", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Apartment", "Apartment")
                        .WithMany("ApartmentBedTypes")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("Apartment_BedType_apartments_Id_fk");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentBenefit", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Apartment", "Apartment")
                        .WithMany("ApartmentBenefits")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("ApartmentBenefits_apartments_Id_fk");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentPublication", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Apartment", "Apartment")
                        .WithMany("ApartmentPublications")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Apartment_Media_Apartment");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Publication", "Media")
                        .WithMany("ApartmentPublications")
                        .HasForeignKey("MediaId")
                        .HasConstraintName("FK_Apartment_Media_Media");

                    b.Navigation("Apartment");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentsAmenity", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Amenity", "Amenity")
                        .WithMany("ApartmentsAmenities")
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK_Amenity");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Apartment", "Apartment")
                        .WithMany("ApartmentsAmenities")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Apartment");

                    b.Navigation("Amenity");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Chat", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "Received")
                        .WithMany("ChatReceiveds")
                        .HasForeignKey("ReceivedId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_User_Receiver");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "Sended")
                        .WithMany("ChatSendeds")
                        .HasForeignKey("SendedId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_User");

                    b.Navigation("Received");

                    b.Navigation("Sended");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.FollowUserAccom", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Accommodation", "Accomodation")
                        .WithMany("FollowUserAccoms")
                        .HasForeignKey("AccomodationId")
                        .IsRequired()
                        .HasConstraintName("FK_Follow_Accom");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "User")
                        .WithMany("FollowUserAccoms")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Follow_User");

                    b.Navigation("Accomodation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.NotificationFollow", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.FollowUserAccom", "Follow")
                        .WithMany("NotificationFollows")
                        .HasForeignKey("FollowId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Follow_Follow");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Notification", "Notification")
                        .WithMany("NotificationFollows")
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Follow_Notification");

                    b.Navigation("Follow");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.NotificationReservation", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Notification", "Notification")
                        .WithMany("NotificationReservations")
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_reservation_Notification");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Reservation", "Reservation")
                        .WithMany("NotificationReservations")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_reservation_Reservation");

                    b.Navigation("Notification");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.NotificationReview", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Notification", "Notifycaton")
                        .WithMany("NotificationReviews")
                        .HasForeignKey("NotifycatonId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Review_Notification");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Review", "Review")
                        .WithMany("NotificationReviews")
                        .HasForeignKey("ReviewId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Review_Review");

                    b.Navigation("Notifycaton");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ReasonReport", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Reason", "Reason")
                        .WithMany("ReasonReports")
                        .HasForeignKey("ReasonId")
                        .IsRequired()
                        .HasConstraintName("FK_Reason_Report_Reason");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Report", "Report")
                        .WithMany("ReasonReports")
                        .HasForeignKey("ReportId")
                        .IsRequired()
                        .HasConstraintName("FK_Reason_Report_Report");

                    b.Navigation("Reason");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Report", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Accommodation", "Accomodation")
                        .WithMany("Reports")
                        .HasForeignKey("AccomodationId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Accommodation");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_user");

                    b.Navigation("Accomodation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Reservation", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Apartment", "Apartment")
                        .WithMany("Reservations")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_Apartment");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "Owner")
                        .WithMany("ReservationOwners")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_User_Owner");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "User")
                        .WithMany("ReservationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_User");

                    b.Navigation("Apartment");

                    b.Navigation("Owner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Review", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Reservation", "Reservation")
                        .WithMany("Reviews")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("reviews_reservation_Id_fk");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("reviews_users_Id_fk");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Transaction", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Accommodation", "Post")
                        .WithMany("Transactions")
                        .HasForeignKey("PostId")
                        .HasConstraintName("Transactions_Accommodations_Id_fk");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Unavailableapartmentdate", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.ApartmentBedType", "ApartmentType")
                        .WithMany("Unavailableapartmentdates")
                        .HasForeignKey("ApartmentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Aprartment");

                    b.Navigation("ApartmentType");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.User", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Publication", "Avatar")
                        .WithMany("UserAvatars")
                        .HasForeignKey("AvatarId")
                        .HasConstraintName("users_Publications_Id_fk");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Publication", "CoverImageNavigation")
                        .WithMany("UserCoverImageNavigations")
                        .HasForeignKey("CoverImage")
                        .HasConstraintName("users_Publications_Id_fk2");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("ForeignKey_Users_Role");

                    b.Navigation("Avatar");

                    b.Navigation("CoverImageNavigation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.UserHighlight", b =>
                {
                    b.HasOne("YghRentalManagementSystem.Infra.Models.Publication", "Publication")
                        .WithMany("UserHighlights")
                        .HasForeignKey("PublicationId")
                        .HasConstraintName("user_highlight_Publications_Id_fk");

                    b.HasOne("YghRentalManagementSystem.Infra.Models.User", "User")
                        .WithMany("UserHighlights")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_highlight_users_UserId_fk");

                    b.Navigation("Publication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Accommodation", b =>
                {
                    b.Navigation("AccommodationPublications");

                    b.Navigation("Apartments");

                    b.Navigation("FollowUserAccoms");

                    b.Navigation("Reports");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Address", b =>
                {
                    b.Navigation("Accommodations");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Amenity", b =>
                {
                    b.Navigation("ApartmentsAmenities");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentBedTypes");

                    b.Navigation("ApartmentBenefits");

                    b.Navigation("ApartmentPublications");

                    b.Navigation("ApartmentsAmenities");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.ApartmentBedType", b =>
                {
                    b.Navigation("Unavailableapartmentdates");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Estatetype", b =>
                {
                    b.Navigation("Accommodations");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.FollowUserAccom", b =>
                {
                    b.Navigation("NotificationFollows");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Notification", b =>
                {
                    b.Navigation("NotificationFollows");

                    b.Navigation("NotificationReservations");

                    b.Navigation("NotificationReviews");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Publication", b =>
                {
                    b.Navigation("AccommodationPublications");

                    b.Navigation("ApartmentPublications");

                    b.Navigation("UserAvatars");

                    b.Navigation("UserCoverImageNavigations");

                    b.Navigation("UserHighlights");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Reason", b =>
                {
                    b.Navigation("ReasonReports");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Report", b =>
                {
                    b.Navigation("ReasonReports");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Reservation", b =>
                {
                    b.Navigation("NotificationReservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Review", b =>
                {
                    b.Navigation("NotificationReviews");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("YghRentalManagementSystem.Infra.Models.User", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Account");

                    b.Navigation("Apartments");

                    b.Navigation("ChatReceiveds");

                    b.Navigation("ChatSendeds");

                    b.Navigation("FollowUserAccoms");

                    b.Navigation("Reports");

                    b.Navigation("ReservationOwners");

                    b.Navigation("ReservationUsers");

                    b.Navigation("Reviews");

                    b.Navigation("UserHighlights");
                });
#pragma warning restore 612, 618
        }
    }
}
